# Generated by Django 4.0.7 on 2022-08-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Task', 'Task'), ('Bug', 'Bug'), ('Feature', 'Feature')], default='Task', max_length=10)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
