# Generated by Django 4.0.7 on 2022-08-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.CharField(choices=[(1, 'Task'), (2, 'Bug'), (3, 'Feature')], default='Task', max_length=10),
        ),
    ]
