# Generated by Django 4.0.7 on 2022-08-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.CharField(choices=[('T', 'Task'), ('Bug', 'Bug'), ('Feature', 'Feature')], default='Task', max_length=10),
        ),
    ]
