# Generated by Django 4.0.7 on 2022-08-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Done', 'Done')], max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.CharField(choices=[('Task', 'Task'), ('Bug', 'Bug'), ('Feature', 'Feature')], max_length=10),
        ),
    ]
